export const diconary = [
  ['auto' , 'Auto', 'Auto'],
  ['on', 'An', 'Aan'],
  ['off', 'aus', 'Uit'],
  ['plant running', 'anlage ein', 'RO aan'],
  ['reset', 'Reset', 'Reset'],
  ['intake', 'Zulauf', 'Inlaat'],
  ['permate', 'Permate', 'Permeaat'],
  ['drain', 'Ablauf', 'Afvoer'],
  ['bar', 'Bar', 'Bar'],
  ['l/min', 'l/min', 'l/min'],
  ['dp', 'Dif', 'Vd'],
  ['differntial pressure', 'Differenzdruck', 'Verschildruk'],
  ['amount raw water', 'Menge Rohwasser', 'Volume Zacht Water'],
  ['amount permate', 'Menge Permate', 'Volume Permeaat'],
  ['amount circulation', 'Menge Zirkulation', 'Volume Recirculatie'],
  ['amount concentrade', 'Menge Konzentrat', 'Volume Concentraat'],
  ['temperature', 'Temperatur', 'Temperatuur'],
  ['start up, flushing without pump', 'Start, spülen ohne Pumpe', 'Opstart, spoelen zonder pomp'],
  ['start up, flushing with pump', 'Start, spülen mit Pumpe', 'Opstart, spoelen met pomp'],
  ['production', 'Produktion', 'Productie'],
  ['shut down, flushing without pump', 'Abschalten, spülen ohne Pumpe', 'uitschakelen, spoelen zonder pomp'],
  ['shut down, flushing with pump', 'Abschalten, spülen mit Pumpe', 'uitschakelen, spoelen met pomp'],
  ['standby', 'Standby', 'Standby'],
  ['Login failed', 'Login fehlgeschlagen', 'Inloggen mislukt'],
  ['login', 'Login', 'Login'],
  ['abort', 'Abbrechen', 'Afbreken'],
  ['email', 'E-mail', 'email'],
  ['password', 'Passwort', 'paswoord'],
  ['constants', 'Konstanten', 'Constantes'],
  ['sensors', 'Sensoren', 'Sensoren'],
  ['plant manual', 'Anlage manuell', 'Handbediening'],
  ['adminpanel', 'Adminpanel', 'Admin Peneel'],
  ['back', 'Zurück', 'Terug'],
  ['max waterlevel', 'Max Wasserniveau', 'Maximum Waterniveau'],
  ['waterlevel offset', 'Wasserlevel start', 'Waterniveau Verschil'],
  ['waterlevel min', 'Wasserstand min', 'Waterniveau Minimum'],
  ['waterlevel max', 'Wasserstand max', 'Waternivaue Maximum'],
  ['timer0_offset', 'Timer0_Zeit', 'Timer0 vertraging'],
  ['timer1_offset', 'Timer1_Zeit', 'Timer1 vertraging'],
  ['timer2_offset', 'Timer2_Zeit', 'Timer2 vertraging'],
  ['timer3_offset', 'Timer3_Zeit', 'Timer3 vertraging'],
  ['timer4_offset', 'Timer4_Zeit', 'Timer4 vertraging'],
  ['timer5_offset', 'Timer5_Zeit', 'Timer5 vertraging'],
  ['timer6_offset', 'Timer6_Zeit', 'Timer6 vertraging'],
  ['timer7_offset', 'Timer7_Zeit', 'Timer7 vertraging'],
  ['ID', 'ID', 'ID'],
  ['name', 'Name', 'Nääm'],
  ['value', 'Wert', 'Waarde'],
  ['comment', 'Kommentar', 'Commentaar'],
  ['request water at', 'Request Wasser ab', 'Watervraag bij'],
  ['request water till', 'Request Wasser bis', 'Watervraag tot'],
  ['english', 'Englisch', 'english'],
  ['german', 'Deutsch', 'german'],
  ['flemish', 'Flämisch', 'flemish'],
  ['remain signed in', 'Angemeldet bleiben', 'remain signed in'],
  ['language', 'Sprache', 'language'],
  ['', '', '']
]
